import { Intent } from "@blueprintjs/core";

export const definition = {
  leave_free: "Tastenfelder frei lassen",
  phones: "Telefone",
  phone_provisioning: "Telefon Config",
  transfer_config: "Konfig Übertragen",
  loading: "Wird geladen ...",
  new_phone: "Neu",
  new_company: "Neuer Kunde",
  name: "Name",
  number: "Nummer",
  ip: "IP",
  label: "Beschrift.",
  value: "Wert",
  copy: "Kopieren",
  save: "Konfig übertragen",
  no_phones: "Keine Telefone",
  create_company: "Erstellen",
  status: "Status",
  nonexistent: "Existiert nicht (keine IP?)",
  online: "Online",
  offline: "Nicht erreichbar",
  softkey: {
    "": "Kein",
    line: "Leitung",
    speeddial: "Direktwahl",
    dnd: "Bitte nicht stören",
    blfprivacy: "BLF Privacy",
    blf: "BLF",
    list: "BLF/Liste",
    acd: "Automatische Anrufverteilung",
    dcp: "Direkt Abnehmen",
    xml: "XML",
    flash: "Flash",
    spre: "Sprecode",
    park: "Parken",
    pickup: "Abnehmen",
    lcr: "Letzter Rückruf",
    callforward: "RufUml.f",
    blfxfer: "BLF/Weiterltg.",
    speeddialxfer: "Direktwahl/Weiterltg.",
    speeddialconf: "Direktwahl/Konf.",
    directory: "Telefonbuch",
    filter: "Filter",
    callers: "Anrufliste",
    redial: "Wahlw.",
    conf: "Konf.",
    xfer: "Weiterl.",
    icom: "Gegenspr.",
    phonelock: "Telefonsperre",
    paging: "Paging",
    hotdesklogin: "Log-In",
    speeddialmwi: "Direktwahl/MWI",
    discreetringing: "Discreet Ringing",
    empty: "Leer"
  }
};

export const softkeyTypes = [
  "",
  "line",
  "speeddial",
  "dnd",
  "blfprivacy",
  "blf",
  "list",
  "acd",
  "dcp",
  "xml",
  "flash",
  "spre",
  "park",
  "pickup",
  "lcr",
  "callforward",
  "blfxfer",
  "speeddialxfer",
  "speeddialconf",
  "directory",
  "filter",
  "callers",
  "redial",
  "conf",
  "xfer",
  "icom",
  "phonelock",
  "paging",
  "hotdesklogin",
  "speeddialmwi",
  "discreetringing",
  "empty"
];

export const TopSoftkeyTypes = {
  None: "",
  Line: "line",
  SpeedDial: "speeddial",
  DoNotDisturb: "dnd",
  BlfPrivacy: "blfprivacy",
  Blf: "blf",
  List: "list",
  Acd: "acd",
  Dcp: "dcp",
  XML: "xml",
  Flash: "flash",
  Spre: "spre",
  Park: "park",
  Pickup: "pickup",
  Lcr: "lcr",
  CallForward: "callforward",
  BlfXfer: "blfxfer",
  SpeedDialXfer: "speeddialxfer",
  SpeedDialConf: "speeddialconf",
  Directory: "directory",
  Filter: "filter",
  Callers: "callers",
  ReDial: "redial",
  Conf: "conf",
  Xfer: "xfer",
  Icom: "icom",
  PhoneLock: "phonelock",
  Paging: "paging",
  HotDeskLogin: "hotdesklogin",
  SpeedDialMwi: "speeddialmwi",
  DiscreetRinging: "discreetringing",
  Empty: "empty"
};

export function toTopSoftkeyEnum(val) {
  return Object.keys(TopSoftkeyTypes)[
    Object.values(TopSoftkeyTypes).indexOf(val)
  ];
}

export const SoftkeyTypes = {
  None: "",
  SpeedDial: "speeddial",
  DoNotDisturb: "dnd",
  XML: "xml",
  Flash: "flash",
  Spre: "spre",
  Park: "park",
  Pickup: "pickup",
  Lcr: "lcr",
  CallForward: "callforward",
  SpeedDialXfer: "speeddialxfer",
  SpeedDialConf: "speeddialconf",
  Directory: "directory",
  Filter: "filter",
  Callers: "callers",
  ReDial: "redial",
  Conf: "conf",
  Xfer: "xfer",
  Icom: "icom",
  PhoneLock: "phonelock",
  Paging: "paging",
  HotDeskLogin: "hotdesklogin",
  DiscreetRinging: "discreetringing",
  History: "callhistory",
  Empty: "empty"
};
